const BD = require("./models/post")

const fix = {
   bdNmame: 'DimaCourse',
   admins: [599773731],
   techChat: process.env.TECH_CHAT,
   errorDone: function(error){if(error.response && error.response.statusCode === 400 || error.response && error.response.statusCode === 403){}},
   helloText: 'С Вами команда Focused✅.\nНаша миссия вывести твою жизнь на новый уровень! 🚀',
   mainMenuText: 'Главное меню',
   toSubText: 'Для доступа подпишись!',
   channelName: 'Канал',
   addCourse: 'Добавить курс',
   courses: 'Курсы',
   toAdminText: 'Admin mode',
   settingsText: 'Настройки',
   addNameText: 'Название курса?',
   addSerieToBot: 'Че лыбишься? Отправь серию боту',
   dellText: 'Удалить',
   backText: 'Назад',
   addSerie: 'Добавить серию',
   payText: 'Платный',
   notPayText: 'Бесплатный',
   vkl: 'Вкл',
   vikl: 'Выкл',
   canselText: 'Отмена',
   countSeries: 'Количество серий:',
   forAllCoursesText: 'Для доступа ко всем курсам купите доступ',
   buyText: 'Купить доступ ко всем курсам!',
   buyLink: 'google.com',
   linkSub: 'https://t.me/+mnmeiBtGRGdmYTJi',
   allAcText: 'Вам доступны все курсы!',
   listCourse: 'Список курсов',
   listSwries: 'Все серии',
   nextText: 'Следующая',
   back1Text: 'Предыдущая',
   reitingText: '📊',
   refreshText: '♻️'
} 

exports.fix = fix